#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-intellij.annotations
Version  : 1
Release  : 1
URL      : https://repo.maven.apache.org/maven2/com/intellij/annotations/9.0.4/annotations-9.0.4-sources.jar
Source0  : https://repo.maven.apache.org/maven2/com/intellij/annotations/9.0.4/annotations-9.0.4-sources.jar
Source1  : https://repo.maven.apache.org/maven2/com/intellij/annotations/9.0.4/annotations-9.0.4.jar
Source2  : https://repo.maven.apache.org/maven2/com/intellij/annotations/9.0.4/annotations-9.0.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-intellij.annotations-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-intellij.annotations package.
Group: Data

%description data
data components for the mvn-intellij.annotations package.


%prep
%setup -q -n org

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/intellij/annotations/9.0.4
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/intellij/annotations/9.0.4/annotations-9.0.4-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/intellij/annotations/9.0.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/intellij/annotations/9.0.4/annotations-9.0.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/intellij/annotations/9.0.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/intellij/annotations/9.0.4/annotations-9.0.4.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/intellij/annotations/9.0.4/annotations-9.0.4-sources.jar
/usr/share/java/.m2/repository/com/intellij/annotations/9.0.4/annotations-9.0.4.jar
/usr/share/java/.m2/repository/com/intellij/annotations/9.0.4/annotations-9.0.4.pom
